### ISSUE TITLE
npm policy disallows package squatting

### ISSUE THREAD

**Issue by quarterto** [IonicaBizau/npmreserve#1]
https://groups.google.com/forum/#!topic/npm-/odEwfBoxwy4
https://docs.npmjs.com/misc/disputes#exceptions

**Comment by IonicaBizau** [comment]
Yep, good to know! :+1: 

However, if I don't abuse this to much I think that's *almost* fine. I'm glad there are humans and not robots. :smile: 

Thanks for links!

**Comment by IonicaBizau** [comment]
:fire: :fire: https://github.com/IonicaBizau/npmreserve/issues/2#issuecomment-132899753
