### ISSUE TITLE
This package is useless

### ISSUE THREAD

**Issue by ebednarz** [IonicaBizau/npmreserve#2]
> Packages must contain some functionality. "Squatting", that is, publishing an empty package to "reserve" a name, is not allowed.

https://docs.npmjs.com/policies/conduct#acceptable-package-content

In other words, consumers don't only violate the npm terms, the won't win any dispute either.

**Comment by IonicaBizau** [comment]
Yes, I will consider deprecating this and unpublishing it from NPM. Honestly, when I wrote it I didn't know that it's a violation of the npm terms. :smile:

**Comment by IonicaBizau** [comment]
Addressed in https://github.com/IonicaBizau/npmreserve/commit/9561e391c41687959f4ed2974e666e8cd0d36e10 and https://github.com/IonicaBizau/npmreserve/commit/296d1012deb53384ac1622f248706db1d5cd3394. :fire: :boom: 

I also [updated the blog article](http://ionicabizau.net/blog/24-reserving-packages-on-npm) in https://github.com/IonicaBizau/ionicabizau.net/commit/15793c313a4509ee487e5fbe7cde93e96b12f16f.

Finally I `npm unpublish`ed the package:

```sh
ionicabizau@notebook:~/Documents/npmreserve$ npm unpublish 
npm ERR! Refusing to delete entire project.
npm ERR! Run with --force to do this.
npm ERR! npm unpublish <project>[@<version>]
ionicabizau@notebook:~/Documents/npmreserve$ npm unpublish --force
npm WARN using --force I sure hope you know what you are doing.
npm http request GET https://registry.npmjs.org/npmreserve?write=true
npm http 200 https://registry.npmjs.org/npmreserve?write=true
npm http request PUT https://registry.npmjs.org/npmreserve/-rev/3-6069684437b9b35da72d62b45964381a
npm http 200 https://registry.npmjs.org/npmreserve/-rev/3-6069684437b9b35da72d62b45964381a
npm http request GET https://registry.npmjs.org/npmreserve
npm http 200 https://registry.npmjs.org/npmreserve
npm http request DELETE https://registry.npmjs.org/npmreserve/-/npmreserve-1.2.0.tgz/-rev/4-f07a1f3187893b083afdb5801a7cbbe6
npm http 200 https://registry.npmjs.org/npmreserve/-/npmreserve-1.2.0.tgz/-rev/4-f07a1f3187893b083afdb5801a7cbbe6
- npmreserve@1.2.0
```

![](http://cdn.smosh.com/sites/default/files/bloguploads/simpsons-fire.gif)

**Comment by ebednarz** [comment]
Thanks :)
